import {
  AlarmClockIcon,
  Backpack01Icon as BackpackIcon,
  ZapIcon as Bolt01Icon,
  Calendar01Icon,
  Calendar03Icon,
  CalendarCheckIn01Icon,
  Camera01Icon,
  CameraAdd01Icon,
  Castle01Icon,
  ChartUpIcon,
  Clock01Icon,
  Compass01Icon,
  CrownIcon as Crown01Icon,
  DeliveryBox01Icon,
  Diamond01Icon,
  EarthIcon,
  EggIcon,
  Fire02Icon,
  FireIcon,
  FireworksIcon,
  FlashIcon,
  Flowchart01Icon,
  GameboyIcon,
  Globe02Icon,
  HourglassIcon,
  MagicWand01Icon,
  Medal01Icon,
  Moon02Icon,
  Package01Icon,
  PuzzleIcon as Puzzle01Icon,
  Rocket01Icon,
  RubiksCubeIcon,
  SafeBoxIcon,
  StarIcon as Star01Icon,
  SunglassesIcon,
  Sword01Icon,
  // 1.0.0 achievement/badge catalog icons
  Time01Icon,
  Time04Icon,
  Timer01Icon,
  Award01Icon as Trophy01Icon,
  UserEdit01Icon as UserEditIcon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";

const ICON_MAP: Record<string, IconSvgElement> = {
  AlarmClockIcon,
  BackpackIcon,
  Bolt01Icon,
  Calendar01Icon,
  Calendar03Icon,
  CalendarCheckIn01Icon,
  Camera01Icon,
  CameraAdd01Icon,
  Castle01Icon,
  ChartUpIcon,
  Clock01Icon,
  Compass01Icon,
  Crown01Icon,
  DeliveryBox01Icon,
  Diamond01Icon,
  EarthIcon,
  EggIcon,
  Fire02Icon,
  FireIcon,
  FireworksIcon,
  FlashIcon,
  Flowchart01Icon,
  GameboyIcon,
  Globe02Icon,
  HourglassIcon,
  MagicWand01Icon,
  Medal01Icon,
  Moon02Icon,
  Package01Icon,
  Puzzle01Icon,
  Rocket01Icon,
  RubiksCubeIcon,
  SafeBoxIcon,
  Star01Icon,
  SunglassesIcon,
  Sword01Icon,
  Time01Icon,
  Time04Icon,
  Timer01Icon,
  Trophy01Icon,
  UserEditIcon,
};

export function resolveIcon(token: string): IconSvgElement {
  return ICON_MAP[token] ?? Star01Icon;
}

export type { IconSvgElement };
export { HugeiconsIcon };
