name = "glitchy-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"
account_id = "7a17f473129a9a71fa4f35ee04e06bbc"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "glitchy-db"
database_id = "glitchy-db"
